In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_json('cve-2002.json')

In [3]:
dataset1 = pd.read_json('cve-2003.json')

In [4]:
dataset2 = pd.read_json('cve-2004.json')

In [5]:
dataset3 = pd.read_json('cve-2005.json')

In [6]:
dataset4 = pd.read_json('cve-2006.json')

In [7]:
dataset5 = pd.read_json('cve-2007.json')

In [8]:
dataset6 = pd.read_json('cve-2008.json')

In [9]:
dataset7 = pd.read_json('cve-2009.json')

In [10]:
dataset8 = pd.read_json('cve-2010.json')

In [11]:
dataset9 = pd.read_json('cve-2011.json')

In [12]:
dataset10 = pd.read_json('cve-2012.json')

In [13]:
dataset11 = pd.read_json('cve-2013.json')

In [14]:
dataset12 = pd.read_json('cve-2014.json')

In [15]:
dataset13 = pd.read_json('cve-2015.json')

In [16]:
dataset14 = pd.read_json('cve-2016.json')

In [17]:
dataset15 = pd.read_json('cve-2017.json')

In [18]:
dataset16 = pd.read_json('cve-2018.json')

In [19]:
dataset.shape

(6745, 6)

In [20]:
dataset16.shape

(13949, 6)

In [21]:
dataset3.columns.values

array(['CVE_Items', 'CVE_data_format', 'CVE_data_numberOfCVEs',
       'CVE_data_timestamp', 'CVE_data_type', 'CVE_data_version'],
      dtype=object)

In [23]:
dataset1.CVE_Items[200]

{'configurations': {'CVE_data_version': '4.0',
  'nodes': [{'cpe': [{'cpe22Uri': 'cpe:/a:rinetd:rinetd:0.52',
      'cpe23Uri': 'cpe:2.3:a:rinetd:rinetd:0.52:*:*:*:*:*:*:*',
      'vulnerable': True},
     {'cpe22Uri': 'cpe:/a:rinetd:rinetd:0.61',
      'cpe23Uri': 'cpe:2.3:a:rinetd:rinetd:0.61:*:*:*:*:*:*:*',
      'vulnerable': True}],
    'operator': 'OR'}]},
 'cve': {'CVE_data_meta': {'ASSIGNER': 'cve@mitre.org', 'ID': 'CVE-2003-0212'},
  'affects': {'vendor': {'vendor_data': [{'product': {'product_data': [{'product_name': 'rinetd',
         'version': {'version_data': [{'version_value': '0.52'},
           {'version_value': '0.61'}]}}]},
      'vendor_name': 'rinetd'}]}},
  'data_format': 'MITRE',
  'data_type': 'CVE',
  'data_version': '4.0',
  'description': {'description_data': [{'lang': 'en',
     'value': 'handleAccept in rinetd before 0.62 does not properly resize the connection list when it becomes full and sets an array index incorrectly, which allows remote attackers to c

In [22]:
new=dataset.CVE_Items[200]

In [23]:
len(new)

5

In [24]:
new['cve']['description']['description_data'][0]['value']

'The GNU tar command, when used in FTP sessions, may allow an attacker to execute arbitrary commands.'

In [28]:
new['impact']['baseMetricV2'][ 'exploitabilityScore']

10.0

In [28]:
new['impact']['baseMetricV2']['severity']

'HIGH'

In [29]:
new.keys()

dict_keys(['cve', 'configurations', 'impact', 'publishedDate', 'lastModifiedDate'])

In [30]:
rev = []
j=0
for i in range(dataset.shape[0]):
    new=dataset.CVE_Items[i]
    if('baseMetricV2' in new['impact'].keys()):
        var=new['impact']['baseMetricV2']['severity']
        rev.append(var)
    else:
        rev.append('Not Exists')
    j=j+1  

In [31]:
rev=np.array(rev)

In [32]:
rev.shape

(6745,)

In [33]:
rev[330]

'HIGH'

In [34]:
num = 0
val = []
for i in range(rev.shape[0]):
    if (rev[i] == 'Not Exists'):
        num = num + 1
        val.append(i)
    

In [35]:
print(num)

78


In [36]:
val=np.array(val)

In [37]:
val.shape

(78,)

In [38]:
description = []
severity = []
scores = []

#for i in range(dataset.shape[0]):
 #   new=dataset.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])

#for i in range(dataset1.shape[0]):
 #   new=dataset1.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
    
#for i in range(dataset2.shape[0]):
 #   new=dataset2.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])

#for i in range(dataset3.shape[0]):
 #   new=dataset3.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])

#for i in range(dataset4.shape[0]):
 #   new=dataset4.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset5.shape[0]):
 #   new=dataset5.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset6.shape[0]):
 #   new=dataset6.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset2.shape[0]):
 #   new=dataset2.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset7.shape[0]):
 #   new=dataset7.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset8.shape[0]):
 #   new=dataset8.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset9.shape[0]):
 #   new=dataset9.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset10.shape[0]):
 #   new=dataset10.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset11.shape[0]):
 #   new=dataset11.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset12.shape[0]):
 #   new=dataset12.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset13.shape[0]):
   # new=dataset13.CVE_Items[i]
    #if('baseMetricV2' in new['impact'].keys()):
        #severity.append(new['impact']['baseMetricV2']['severity'])
        #scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
        #description.append(new['cve']['description']['description_data'][0]['value'])
        
#for i in range(dataset14.shape[0]):
 #   new=dataset14.CVE_Items[i]
  #  if('baseMetricV2' in new['impact'].keys()):
   #     severity.append(new['impact']['baseMetricV2']['severity'])
    #    scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
     #   description.append(new['cve']['description']['description_data'][0]['value'])
        
for i in range(dataset15.shape[0]):
    new=dataset15.CVE_Items[i]
    if('baseMetricV2' in new['impact'].keys()):
        severity.append(new['impact']['baseMetricV2']['severity'])
        scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
        description.append(new['cve']['description']['description_data'][0]['value'])
        
for i in range(dataset16.shape[0]):
    new=dataset16.CVE_Items[i]
    if('baseMetricV2' in new['impact'].keys()):
        severity.append(new['impact']['baseMetricV2']['severity'])
        scores.append(new['impact']['baseMetricV2']['cvssV2']['baseScore'])
        description.append(new['cve']['description']['description_data'][0]['value'])

In [39]:
description = np.array(description)
severity = np.array(severity)
scores = np.array(scores)

In [40]:
scores.shape

(24281,)

In [41]:
severity.shape

(24281,)

In [42]:
description.shape

(24281,)

In [43]:
description[200]

'Microsoft Windows 10 Gold, Windows 10 1511, Windows 10 1607, and Windows Server 2016 allow an attacker to exploit a security feature bypass vulnerability in Device Guard that could allow the attacker to inject malicious code into a Windows PowerShell session, aka "Device Guard Code Integrity Policy Security Feature Bypass Vulnerability." This CVE ID is unique from CVE-2017-0173, CVE-2017-0215, CVE-2017-0216, and CVE-2017-0218.'

In [44]:
severity[200]

'MEDIUM'

In [45]:
scores[200]

4.6

In [46]:
from bs4 import BeautifulSoup  
import re
from nltk.corpus import stopwords
def review_to_words( raw_review ):
    # Function to convert a raw review to a string of words
    # The input is a single string (a raw movie review), and 
    # the output is a single string (a preprocessed movie review)
    #
    # 1. Remove HTML
    review_text = BeautifulSoup(raw_review).get_text() 
    #
    # 2. Remove non-letters        
    letters_only = re.sub("[^a-zA-Z]", " ", review_text) 
    #
    # 3. Convert to lower case, split into individual words
    words = letters_only.lower().split()                             
    #
    # 4. In Python, searching a set is much faster than searching
    #   a list, so convert the stop words to a set
    stops = set(stopwords.words("english"))                  
    # 
    # 5. Remove stop words
    meaningful_words = [w for w in words if not w in stops]   
    #
    # 6. Join the words back into one string separated by space, 
    # and return the result.
    return( " ".join( meaningful_words )) 

In [47]:
# Get the number of reviews based on the dataframe column size

# Initialize an empty list to hold the clean reviews
clean_description = []

# Loop over each review; create an index i that goes from 0 to the length
# of the movie review list 
for i in range(description.shape[0]):
    # Call our function for each one, and add the result to the list of
    # clean reviews
    clean_description.append( review_to_words( description[i] ) )

In [48]:
clean_description[200]

'microsoft windows gold windows windows windows server allow attacker exploit security feature bypass vulnerability device guard could allow attacker inject malicious code windows powershell session aka device guard code integrity policy security feature bypass vulnerability cve id unique cve cve cve cve'

In [49]:
clean_description_array = np.array(clean_description)

In [50]:
print ("Creating the bag of words...\n")
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the "CountVectorizer" object, which is scikit-learn's
# bag of words tool.  
vectorizer = CountVectorizer(analyzer = "word",   \
                             tokenizer = None,    \
                             preprocessor = None, \
                             stop_words = None,   \
                             max_features = 500) 

# fit_transform() does two functions: First, it fits the model
# and learns the vocabulary; second, it transforms our training data
# into feature vectors. The input to fit_transform should be a list of 
# strings.
description_features = vectorizer.fit_transform(clean_description_array)

# Numpy arrays are easy to work with, so convert the result to an 
# array
description_features = description_features.toarray()

Creating the bag of words...



In [51]:
description_features.shape

(24281, 500)

In [118]:
from sklearn.cross_validation import StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
n_folds = 5
score = 0.0
skf = StratifiedKFold(severity, n_folds)
avg_score = 0

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = severity[train_index], severity[test_index]
    forest = RandomForestClassifier(n_estimators = 50)
    forest.fit( X_train, y_train )
    score = forest.score(X_test,y_test)
    avg_score += score 
    print(score)
    
print("avg",avg_score/n_folds)

0.982297241663236
0.992998352553542
0.984349258649094
0.9892915980230642
0.9936148300720906
avg 0.9885102561922053


In [52]:
score_result = np.array(scores).astype(np.float)
score_result.shape[0]

24281

In [88]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error,mean_absolute_error

n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)



for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
    params = {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 2,
          'learning_rate': 0.01, 'loss': 'ls'}
    clf = ensemble.GradientBoostingRegressor(**params)
    clf.fit(X_train, y_train)
    mse = mean_squared_error(y_test, clf.predict(X_test))
    mad = mean_absolute_error(y_test, clf.predict(X_test))
    #print("MSE: %.4f" % mse)
    avg_mad += mad
    print("MAE: %.4f" % mad)
print("avg",avg_mad/n_folds)    

MAE: 0.9474
MAE: 0.8387
MAE: 0.8164
MAE: 0.8271


KeyboardInterrupt: 

In [37]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.preprocessing import StandardScaler

n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
    params = {'n_estimators': 500, 'max_depth': 8, 'min_samples_split': 2,
          'learning_rate': 0.01, 'loss': 'ls'}
    
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    clf = ensemble.GradientBoostingRegressor(**params)
    clf.fit(X_train, y_train)
    mse = mean_squared_error(y_test, clf.predict(X_test))
    mad = mean_absolute_error(y_test, clf.predict(X_test))
    #print("MSE: %.4f" % mse)
    avg_mad += mad
    print("MAE: %.4f" % mad)
print("avg",avg_mad/n_folds)  

MAE: 0.9656
MAE: 0.9153


KeyboardInterrupt: 

In [57]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Activation
import matplotlib.pyplot as plt
from sklearn.cross_validation import StratifiedKFold


n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]

    
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    

    
    
    # Initialising the ANN
    model1 = Sequential()

    # Adding the input layer and the first hidden layer
    model1.add(Dense(32, activation = 'relu', input_dim = 500))

    # Adding the second hidden layer
    model1.add(Dense(units = 32, activation = 'relu'))

    # Adding the third hidden layer
    model1.add(Dense(units = 32, activation = 'relu'))

    # Adding the output layer

    model1.add(Dense(units = 1))

    #model.add(Dense(1))
    # Compiling the ANN
    model1.compile(optimizer = 'sgd', loss = 'mean_absolute_error')

    # Fitting the ANN to the Training set
    model1.fit(X_train, y_train, batch_size = 10, epochs = 22, shuffle = True)

    mad1 = mean_squared_error(y_test, model1.predict(X_test))
    avg_mad += mad1
    print("MAE: %.4f" % mad1)
print("avg",avg_mad/n_folds)     

Epoch 1/22
19398/19398 [==============================] - 3s 133us/step - loss: 1.0922
Epoch 2/22
19398/19398 [==============================] - 2s 119us/step - loss: 0.8277
Epoch 3/22
19398/19398 [==============================] - 2s 121us/step - loss: 0.7610
Epoch 4/22
19398/19398 [==============================] - 2s 119us/step - loss: 0.7158
Epoch 5/22
19398/19398 [==============================] - 2s 120us/step - loss: 0.6745
Epoch 6/22
19398/19398 [==============================] - 2s 120us/step - loss: 0.6394
Epoch 7/22
19398/19398 [==============================] - 2s 121us/step - loss: 0.6154
Epoch 8/22
19398/19398 [==============================] - 2s 122us/step - loss: 0.5911
Epoch 9/22
19398/19398 [==============================] - 2s 123us/step - loss: 0.5683
Epoch 10/22
19398/19398 [==============================] - 2s 123us/step - loss: 0.5525
Epoch 11/22
19398/19398 [==============================] - 3s 130us/step - loss: 0.5334
Epoch 12/22
19398/19398 [================

# CNNS

In [ ]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense, Activation
import matplotlib.pyplot as plt
from sklearn.cross_validation import StratifiedKFold
from keras.layers import Conv2D 

n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
  
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    
    
    # Initialising the ANN
    model = Sequential()

    model.add(Conv2D(32, kernel_size=(3,3), input_shape=(X_train.shape[0],500,1), padding='same', activation='relu'))
    model.add(Conv2D(64, kernel_size=(3,3), padding='same', activation='relu'))
    model.add(Dense(1024, activation='relu'))
    model.add(Dense(10,activation='softmax'))
    
    
    model.add(Dense(3))
    # Compiling the ANN
    model.compile(optimizer = 'adam', loss = 'mean_absolute_error')
    
    
    X_train.resize((1,X_train.shape[0],X_train.shape[1],1))
    y_train.resize((1,y_train.shape[0],500,1))
    # Fitting the ANN to the Training set
    model.fit(X_train, y_train, batch_size = 10, epochs = 20, shuffle = True,validation_data=(X_train,y_train))

    mad = mean_squared_error(y_test, model.predict(X_test))
    print("MAE: %.4f" % mad)
  


# Deep Tensor 

In [ ]:
import os
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler

In [95]:
from sklearn import ensemble
from sklearn.metrics import mean_squared_error,mean_absolute_error


n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    Y_train, Y_test = score_result[train_index], score_result[test_index]
    
    
    # Define model parameters
    learning_rate = 0.001
    training_epochs = 500

    # Define how many inputs and outputs are in our neural network
    number_of_inputs = 500
    number_of_outputs = 1

    # Define how many neurons we want in each layer of our neural network
    layer_1_nodes = 50
    layer_2_nodes = 100
    layer_3_nodes = 50
    
    tf.reset_default_graph()
    
    # Input Layer
    with tf.variable_scope('input'):
        X = tf.placeholder(tf.float32, shape=(None, number_of_inputs))

    # Layer 1
    with tf.variable_scope('layer_1'):
        weights = tf.get_variable("weights1", shape=[number_of_inputs, layer_1_nodes], initializer=tf.contrib.layers.xavier_initializer())
        biases = tf.get_variable(name="biases1", shape=[layer_1_nodes], initializer=tf.zeros_initializer())
        layer_1_output = tf.nn.relu(tf.matmul(X, weights) + biases)

    # Layer 2
    with tf.variable_scope('layer_2'):
        weights = tf.get_variable("weights2", shape=[layer_1_nodes, layer_2_nodes], initializer=tf.contrib.layers.xavier_initializer())
        biases = tf.get_variable(name="biases2", shape=[layer_2_nodes], initializer=tf.zeros_initializer())
        layer_2_output = tf.nn.relu(tf.matmul(layer_1_output, weights) + biases)

    # Layer 3
    with tf.variable_scope('layer_3'):
        weights = tf.get_variable("weights3", shape=[layer_2_nodes, layer_3_nodes], initializer=tf.contrib.layers.xavier_initializer())
        biases = tf.get_variable(name="biases3", shape=[layer_3_nodes], initializer=tf.zeros_initializer())
        layer_3_output = tf.nn.relu(tf.matmul(layer_2_output, weights) + biases)

    # Output Layer
    with tf.variable_scope('output'):
        weights = tf.get_variable("weights4", shape=[layer_3_nodes, numbe zer())
        biases = tf.get_variable(name="biases4", shape=[number_of_outputs], initializer=tf.zeros_initializer())
        prediction = tf.matmul(layer_3_output, weights) + biases

    # Section Two: Define the cost function of the neural network that will measure prediction accuracy during training

    with tf.variable_scope('cost'):
        Y = tf.placeholder(tf.float32)
        cost = tf.reduce_mean(abs(prediction-Y))
    
    # Section Three: Define the optimizer function that will be run to optimize the neural network

    with tf.variable_scope('train'):
        optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)
    
    # Initialize a session so that we can run TensorFlow operations
    with tf.Session() as session:

        # Run the global variable initializer to initialize all variables and layers of the neural network
        session.run(tf.global_variables_initializer())

        # Run the optimizer over and over to train the network.
        # One epoch is one full run through the training data set.
        for epoch in range(training_epochs):

            # Feed in the training data and do one step of neural network training
            session.run(optimizer, feed_dict={X: X_train, Y: Y_train})

            # Every 5 training steps, log our progress
            if epoch % 5 == 0:
                training_cost = session.run(cost, feed_dict={X: X_train, Y:Y_train})
                testing_cost = session.run(cost, feed_dict={X: X_test, Y:Y_test})

                print(epoch, training_cost, testing_cost)

        # Training is now complete!
        print("Training is complete!")

        final_training_cost = session.run(cost, feed_dict={X: X_train, Y: Y_train})
        final_testing_cost = session.run(cost, feed_dict={X: X_test, Y: Y_test})

        print("Final Training cost: {}".format(final_training_cost))
        print("Final Testing cost: {}".format(final_testing_cost))
    

0 [[6.3652406 6.3652406 6.3652406 ... 6.4652405 4.2652407 4.2652407]
 [6.3652406 6.3652406 6.3652406 ... 6.4652405 4.2652407 4.2652407]
 [6.380944  6.380944  6.380944  ... 6.4809437 4.280944  4.280944 ]
 ...
 [6.3446207 6.3446207 6.3446207 ... 6.4446206 4.244621  4.244621 ]
 [6.4085917 6.4085917 6.4085917 ... 6.5085917 4.308592  4.308592 ]
 [6.454924  6.454924  6.454924  ... 6.554924  4.354924  4.354924 ]] [[7.5131545 9.213155  4.213155  ... 7.8131547 2.2131546 3.6131546]
 [7.4333844 9.133385  4.1333847 ... 7.7333846 2.1333842 3.5333843]
 [7.465279  9.165279  4.1652794 ... 7.7652793 2.1652794 3.5652795]
 ...
 [7.5428405 9.242841  4.242841  ... 7.8428407 2.2428405 3.6428406]
 [7.633146  9.333146  4.333146  ... 7.933146  2.333146  3.7331462]
 [7.557093  9.257093  4.2570934 ... 7.8570933 2.2570934 3.6570935]]
5 [[5.7015676 5.7015676 5.7015676 ... 5.8015676 3.6015677 3.6015677]
 [5.7015676 5.7015676 5.7015676 ... 5.8015676 3.6015677 3.6015677]
 [5.8632126 5.8632126 5.8632126 ... 5.9632125 

50 [[0.1427002  0.1427002  0.1427002  ... 0.2427001  1.9572997  1.9572997 ]
 [0.1427002  0.1427002  0.1427002  ... 0.2427001  1.9572997  1.9572997 ]
 [0.25236702 0.25236702 0.25236702 ... 0.35236692 1.8476329  1.8476329 ]
 ...
 [1.3483019  1.3483019  1.3483019  ... 1.248302   3.4483018  3.4483018 ]
 [2.9552727  2.9552727  2.9552727  ... 3.0552726  0.85527277 0.85527277]
 [2.138188   2.138188   2.138188   ... 2.2381878  0.03818798 0.03818798]] [[2.105001   3.8050013  1.1949987  ... 2.4050012  3.194999   1.7949989 ]
 [2.1241922  3.8241925  1.1758075  ... 2.4241924  3.1758077  1.7758076 ]
 [1.8947768  3.594777   1.4052229  ... 2.194777   3.4052231  2.005223  ]
 ...
 [3.6612616  5.361262   0.36126184 ... 3.9612617  1.6387384  0.2387383 ]
 [1.5516386  3.251639   1.7483611  ... 1.8516388  3.7483613  2.3483613 ]
 [0.90448475 2.604485   2.395515   ... 1.2044849  4.3955154  2.995515  ]]
55 [[0.09928226 0.09928226 0.09928226 ... 0.19928217 2.0007176  2.0007176 ]
 [0.09928226 0.09928226 0.0992822

KeyboardInterrupt: 

# Deep Tensor Ends

In [127]:
temp = description_features[900:901,0:500]

In [128]:
temp.shape

(1, 500)

In [129]:
clf.predict(temp)

AttributeError: 'NoneType' object has no attribute 'tree_'

In [130]:
scores[900]

4.3

In [133]:
from sklearn.ensemble import RandomForestRegressor

n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)



for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
  
    clf = RandomForestRegressor(max_depth=45, random_state=0)
    clf.fit(X_train, y_train)
    mse = mean_squared_error(y_test, clf.predict(X_test))
    mad = mean_absolute_error(y_test, clf.predict(X_test))
    #print("MSE: %.4f" % mse)
    avg_mad += mad
    print("MAE: %.4f" % mad)
print("avg",avg_mad/n_folds)    

MAE: 0.4020
MAE: 0.3440
MAE: 0.4114
MAE: 0.3694
MAE: 0.3967
avg 0.3846973938856226


In [51]:
from sklearn.tree import DecisionTreeRegressor
n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)



for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
    clf = DecisionTreeRegressor(max_depth=45)
    clf.fit(X_train, y_train)
    mse = mean_squared_error(y_test, clf.predict(X_test))
    mad = mean_absolute_error(y_test, clf.predict(X_test))
    #print("MSE: %.4f" % mse)
    avg_mad += mad
    print("MAE: %.4f" % mad)
print("avg",avg_mad/n_folds)  

NameError: name 'score_result' is not defined

In [49]:
from sklearn.ensemble import AdaBoostRegressor

n_folds = 5
avg_mad = 0
skf = StratifiedKFold(score_result, n_folds)

rng = np.random.RandomState(1)

for train_index, test_index in skf:
    X_train, X_test = description_features[train_index], description_features[test_index]
    y_train, y_test = score_result[train_index], score_result[test_index]
    clf = AdaBoostRegressor(DecisionTreeRegressor(max_depth=24),
                          n_estimators=300, random_state=rng)
    clf.fit(X_train, y_train)
    mse = mean_squared_error(y_test, clf.predict(X_test))
    mad = mean_absolute_error(y_test, clf.predict(X_test))
    #print("MSE: %.4f" % mse)
    avg_mad += mad
    print("MAE: %.4f" % mad)
print("avg",avg_mad/n_folds)  

NameError: name 'score_result' is not defined